config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#splash"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :users, only: [:show]
  resources :pages
  resources :categories, only: %i[index new show create edit update destroy]
  resources :expenses, only: %i[new create edit update destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, length: { minimum: 3 },
                   uniqueness: { scope: :user, message: 'Category with this name already exist' }
  validates :icon, presence: true

  belongs_to :user, class_name: 'User', foreign_key: 'author_id'

  has_many :expense_categories, foreign_key: 'category_id', dependent: :destroy
  has_many :expenses, through: :expense_categories, dependent: :destroy

  ICONS = %i[accounting bank books classroom dumbbell diet education family fish piggy-bank religion spiritual sports
             tax user vegetable].freeze
end

app/models/expense.rb
class Expense < ApplicationRecord
  validates :name, presence: true
  validates :amount, presence: true,
                     numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  belongs_to :user, class_name: 'User', foreign_key: 'author_id'

  has_many :expense_categories, foreign_key: 'expense_id',
                                dependent: :destroy
  has_many :categories, through: :expense_categories, dependent: :destroy
end

app/models/expense_category.rb
class ExpenseCategory < ApplicationRecord
  belongs_to :category
  belongs_to :expense
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :trackable

  validates :name, presence: true
  validates :email, presence: true, uniqueness: { case_sensitive: false }
  validates :password, presence: true

  has_many :categories, foreign_key: 'author_id', dependent: :destroy
  has_many :expenses, foreign_key: 'author_id', dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:splash]
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email password])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name email password current_password])
  end

  private

  def after_sign_out_path_for(_resource_or_scope)
    new_user_session_path
  end

  def after_sign_in_path_for(_resource_or_scope)
    categories_path
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = current_user.categories.order(created_at: :desc)
    @total = calculate_total
  end

  def show
    @category = Category.find(params[:id])
    @expenses = ExpenseCategory.all.where(category_id: @category.id).includes(:expense).order(created_at: :desc)
    @total_expenses = obtain_total
  end

  def new
    @category = Category.new
  end

  def create
    category = Category.new(category_params)
    user = current_user
    category.user = user
    if category.save
      redirect_to category, notice: 'Budget category was successfully created.'
    else
      render :new, notice: 'Something went wrong! Budget category was not created'
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    category = Category.find(params[:id])
    if category.update(category_params)
      redirect_to category, notice: 'Budget category was successfully updated.'
    else
      flash[:notice] = 'Something went wrong! Budget category was not updated'
    end
  end

  def destroy
    category = Category.find(params[:id])
    if category.destroy
      redirect_to categories_url, notice: 'Budget category was successfully destroyed.'
    else
      render category, notice: 'Something went wrong! Budget category was not destroyed'
    end
  end

  private

  def category_params
    params.require(:category).permit(:name, :icon)
  end

  def obtain_total
    sum = 0
    @expenses.each do |exp|
      sum += exp.expense.amount.to_i
    end
    sum
  end

  def calculate_total
    sum = 0
    exp = ExpenseCategory.all
    exp.each do |cat|
      sum += cat.expense.amount.to_i
    end
    sum
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  def new
    @expense = Expense.new
    @categories = current_user.categories
    @expense_categories = @expense.expense_categories.build
  end

  def create
    expense = Expense.new(expense_params.except(:expense_categories))
    expense.author_id = current_user.id

    if expense.save
      category = expense_params[:expense_categories][:category_ids][1]
      expense_params[:expense_categories][:category_ids].each do |id|
        expense.expense_categories.create(category_id: id) unless id == ''
      end
      redirect_to category_path(category), notice: 'Budget was successfully created.'
    else
      render expense, alert: 'Something went wrong! Budget expense was not created.'
    end
  end

  def edit
    @expense = Expense.find(params[:id])
    @categories = current_user.categories
    @expense_categories = @expense.expense_categories.build
  end

  def update
    expense = Expense.find(params[:id])
    if expense.update(expense_params.except(:expense_categories))
      category = expense_params[:expense_categories][:category_ids][1]
      redirect_to category_path(category), notice: 'Budget expense successfully updated.'
    else
      flash[:alert] = 'Something went wrong! Budget expense was not updated'
      redirect_to edit_expense_path(expense)
    end
  end

  def destroy
    @expense = Expense.find(params[:id])
    @expo = ExpenseCategory.all.where(expense_id: @expense.id)[0]
    @category = @expo.category
    @expense.destroy
    redirect_to category_path(@category), notice: 'Expense successfully deleted.'
  end

  private

  def expense_params
    params.require(:new_expense).permit(:name, :amount, expense_categories: [category_ids: []])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def splash
    return unless current_user

    redirect_to user_url(current_user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
    @total_categories = current_user.categories.size
    @total_expenses = calculate_total
  end

  private

  def calculate_total
    sum = 0
    current_user.categories.each do |cat|
      sum += ExpenseCategory.all.where(category_id: cat.id).size
    end
    sum
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/edit.html.erb
<section class="category">
  <%= form_with model: @category, url: category_path, method: :put, locals: true, scope: :category, class: "category-form" do |f| %>

    <div class="field">
      <%= f.text_field :name, placeholder: "Category name", autofocus: true, class: "input" %>
    </div>

    <div class="check-box-field">
      <p class="sign-link">Select an icon for category</p>
      <div class="check-boxes">
        <% Category::ICONS.each do |i| %>
      <span>
        <%= f.radio_button :icon, "https://raw.githubusercontent.com/PraisesPJMT/Data/main/categories/#{i}.png", id: i %>
        <label for="<%=i%>" class="custom-radio">
        <img src="https://raw.githubusercontent.com/PraisesPJMT/Data/main/categories/<%= i %>.png" class="select-icon" alt=<%= i %>>
      </label>
      </span>
        <% end %>
      </div>
    </div>

    <div class="btn-container">
      <%= f.submit "UPDATE CATEGORY", class: "btn secondary-btn"  %>
      <%= link_to "BACK TO CATEGORY", :back, class: "btn primary-btn"%>
    </div>
  <% end %>
</section>

app/views/categories/index.html.erb
<section class="category-sec">
  <p class="cat-total">
    <% if @categories.any? %>
      <span class="cat-card-name">Total Budget</span>
      <span class="cat-card-amount">$<%= @total %></span>
    <% else %>
      <span class="cat-card-name">No budget has been created yet. Use the <b>NEW CATEGORY</b> button below to create a budget.</span>
    <% end %>
  </p>
  <% if @categories.any? %>
    <div class="category-wrapper">
      <% @categories.each do |category| %>
        <%= link_to category_path(category), class: "category-card" do %>
          <img class="category-img" src=<%=category.icon%> alt=<%=category.name %> />
          <div class="cat-card-info">
            <p class="cat-det">
              <span class="cat-card-name"><%= category.name %></span>
              <span class="cat-card-amount">$<%= category.expenses.sum(:amount) %></span>
            </p>
            <p class="cat-date"><%= category.created_at.strftime("%d %B %Y at %I:%M %p") %></p>
          </div>
        <% end %>
      <% end %>
    </div>
  <% end %>
  <%= link_to "NEW CATEGORY", new_category_path, class: "btn secondary-btn" %>
</section>

app/views/categories/new.html.erb
<section class="category">
  <%= form_with model: @category, url: categories_path, method: :post, locals: true, scope: :category, class: "category-form" do |f| %>

    <div class="field">
      <%= f.text_field :name, placeholder: "Category name", autofocus: true, class: "input" %>
    </div>

    <div class="check-box-field">
      <p class="sign-link">Select an icon for category</p>
      <div class="check-boxes">
        <% Category::ICONS.each do |i| %>
          <span>
            <%= f.radio_button :icon, "https://raw.githubusercontent.com/PraisesPJMT/Data/main/categories/#{i}.png", id: i %>
            <label for="<%=i%>" class="custom-radio">
              <img src="https://raw.githubusercontent.com/PraisesPJMT/Data/main/categories/<%= i %>.png" class="select-icon" alt=<%= i %>>
            </label>
          </span>
        <% end %>
      </div>
    </div>

<!--    <div class="actions">-->
      <%#= f.submit "CREATE CATEGORY", class: "btn secondary-btn"  %>
<!--    </div>-->

    <div class="btn-container">
      <%= f.submit "CREATE CATEGORY", class: "btn secondary-btn"  %>
      <%= link_to "BACK TO CATEGORY", :back, class: "btn primary-btn"%>
    </div>

  <% end %>
</section>

app/views/categories/show.html.erb
<section class="category-section">
  <div class="cat-container">
    <div class="cat">
      <img class="category-img" src=<%=@category.icon%> alt=<%=@category.name %> />
      <div class="cat-card-info">
        <p class="cat-det">
          <span class="cat-sec-name"><%= @category.name %></span>
          <span class="cat-card-amount">$<%= @total_expenses %></span>
        </p>
        <div class="cat-sec-date">
          <p><%= @category.created_at.strftime("%d ") + @category.created_at.strftime("%B")[0..2] + @category.created_at.strftime(" %Y at %I:%M %p") %></p>
          <div class="sm-btn-card">
            <%= button_to "EDIT", edit_category_path(@category), method: :get, class: "sm-btn primary-btn" %>
            <%= button_to "DELETE", category_path(@category), method: :delete, class: "sm-btn delete-btn"%>
          </div>
        </div>
      </div>
    </div>

    <% if @expenses.any? %>
      <% @expenses.each do |trans| %>
        <div class="trans-card">
          <p class="trans-sec-total">
            <span class="cat-sec-name"><%= trans.expense.name %></span>
            <span class="cat-card-amount">$<%= trans.expense.amount %></span>
          </p>
          <div class="trans-date">
            <p><%= trans.expense.created_at.strftime("%d ") + trans.expense.created_at.strftime("%B")[0..2] + trans.expense.created_at.strftime(" %Y at %I:%M %p") %></p>
            <div class="sm-btn-card">
              <%= button_to "EDIT", edit_expense_path(trans.expense), method: :get, class: "sm-btn primary-btn" %>
              <%= button_to "DELETE", expense_path(trans.expense), method: :delete, class: "sm-btn delete-btn"%>
            </div>
          </div>
        </div>
      <% end %>

      <p class="cat-sec-total">
        <span class="cat-sec-name">TOTAL TRANSACTIONS</span>
        <span class="cat-card-amount">$<%= @total_expenses %></span>
      </p>
  <% end %>

  </div>

  <div class="btn-container">
    <%= link_to "NEW TRANSACTION", new_expense_path, class: "btn secondary-btn" %>
  </div>
</section>

app/views/expenses/edit.html.erb
<section class="transaction">
  <%= form_with model: @expense, method: :put, scope: :new_expense do |f| %>
    <div class="field">
      <%= f.text_field :name, autofocus: true, placeholder: 'Transaction name', class: "input", required: true %>
    </div>

    <div class="field">
      <%= f.number_field :amount, autofocus: true, placeholder: 'Amount ($)', class: "input", required: true %>
    </div>

    <div class="field">
      <%= f.fields_for :expense_categories do |cp| %>
        <%= cp.label :category_ids, 'Select category (at least one)', class: 'sign-link' %> <br>
        <%= cp.collection_select :category_ids, @categories, :id, :name, {}, { multiple: true, required: true, class: "input", size: 2 } %>
      <% end %>
    </div>


    <div class="btn-container">
      <%= f.submit "UPDATE TRANSACTION", class: "btn secondary-btn"  %>
      <%= link_to "BACK TO CATEGORY", :back, class: "btn primary-btn"%>
    </div>

  <% end %>
</section>

app/views/expenses/new.html.erb
<section class="transaction">
  <%= form_with model: @expense, method: :post, scope: :new_expense do |f| %>
    <div class="field">
      <%= f.text_field :name, autofocus: true, placeholder: 'Transaction name', class: "input", required: true %>
    </div>

    <div class="field">
      <%= f.number_field :amount, autofocus: true, placeholder: 'Amount ($)', class: "input", required: true %>
    </div>

    <div class="field">
      <%= f.fields_for :expense_categories do |cp| %>
        <%= cp.label :category_ids, 'Select category (at least one)', class: 'sign-link' %> <br>
        <%= cp.collection_select :category_ids, @categories, :id, :name, {}, { multiple: true, required: true, class: "input", size: 2 } %>
      <% end %>
    </div>


    <div class="btn-container">
      <%= f.submit "CREATE TRANSACTION", class: "btn secondary-btn"  %>
      <%= link_to "BACK TO CATEGORY", :back, class: "btn primary-btn"%>
    </div>

  <% end %>
</section>

app/views/layouts/_header.html.erb
<header>
  <% if request.path == root_path || request.path == categories_path %>
    <button type="button" title="mobile menu open button" class="menu-btn h-btn">
      <span class="bar"></span>
    </button>
  <% else %>
    <%= link_to categories_path, class: "nav-btn h-btn" do %>
      <span class="ptr"></span>
    <% end %>
  <% end %>

  <% if request.path == new_user_registration_path %>
    <h3 class="nav-header">REGISTER</h3>
  <% elsif request.path == new_user_session_path %>
    <h3 class="nav-header">LOG IN</h3>
  <% elsif request.path == new_user_password_path or request.path == edit_user_password_path %>
    <h3 class="nav-header">PASSWORD</h3>
  <% elsif current_user && request.path == user_path(current_user) %>
    <h3 class="nav-header">PROFILE</h3>
  <% elsif current_user && request.path == edit_user_registration_path(current_user) %>
    <h3 class="nav-header">EDIT PROFILE</h3>
  <% elsif current_user && request.path == user_path(current_user) %>
    <h3 class="nav-header">USER</h3>
  <% elsif request.path == categories_path %>
    <h3 class="nav-header">CATEGORIES</h3>
  <% elsif request.path == new_category_path %>
    <h3 class="nav-header">CATEGORY</h3>
  <% elsif request.path.to_s.include?("edit") && request.path.to_s.include?("categories") %>
    <h3 class="nav-header">EDIT CATEGORY</h3>
  <% else %>
    <h3 class="nav-header">TRANSACTIONS</h3>
  <% end %>

  <% if current_user %>
    <%= link_to user_path(current_user), class: "user-avatar h-btn" do %>
        <span class="user-initial"><%= current_user.name.split.map(&:first).join.upcase %></span>
    <% end %>
  <% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fruugal</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <main>
      <% if notice %>
        <p class="notice"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert"><%= alert %></p>
      <% end %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/splash.html.erb
<section class="splash">
  <div class="splash-logo-container">
    <h2 class="splash-logo">Fruugal</h2>
  </div>

  <div class="splash-btn-wrapper">
    <%= link_to "LOG IN", new_user_session_path, class: "btn primary-btn" %><br />
    <%= link_to "SIGN UP", new_user_registration_path, class: "btn tertiary-btn" %><br />
  </div>
</section>

app/views/users/show.html.erb
<section class="user">
  <h1 class="sub-title"><%= @user.name %> Profile</h1>
  <div class="user-section">
    <p><span class="user-detail">Name: </span> <%= @user.name %></p>
    <p><span class="user-detail">Email: </span> <%= @user.email %></p>
  </div>

  <div class="user-section">
    <h3 class="sub-heading">Session Info</h3>
    <p><span class="user-detail">Session count: </span> <%= @user.sign_in_count %></p>
    <p>
      <span class="user-detail">Current sign-in: </span>
      <%= @user.current_sign_in_at.strftime("%d ") + @user.current_sign_in_at.strftime("%B")[0..2] + @user.current_sign_in_at.strftime(" %Y at %I:%M %p") %>
    </p>
    <p>
      <span class="user-detail">Last sign-in: </span>
      <%= @user.last_sign_in_at.strftime("%d ") + @user.last_sign_in_at.strftime("%B")[0..2] + @user.last_sign_in_at.strftime(" %Y at %I:%M %p") %>
    </p>
  </div>

  <div class="user-section">
    <h3 class="sub-heading">Budget Info</h3>
    <p><span class="user-detail">Budget count: </span><%= @total_categories %></p>
    <p><span class="user-detail">Expense count: </span><%= @total_expenses %></p>
  </div>

  <div class="btn-container">
    <%= link_to "VIEW BUDGETS", categories_path, class: "btn primary-btn"%>
    <%= link_to "EDIT PROFILE", edit_user_registration_path(current_user), class: "btn secondary-btn"%>
    <%= button_to "LOG OUT", destroy_user_session_path, method: :delete, class: "btn delete-btn"%>
  </div>
</section>